environment:
  TWINE_PASSWORD:
    secure: 7/AZVv0ovctfsb6fBFuC84eyDbvrPSwFlwtIR5RKvQ0=
  matrix:

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python38-x64"
      MINICONDA: "C:\\Miniconda3-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python37-x64"
      MINICONDA: "C:\\Miniconda3-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python36-x64"
      MINICONDA: "C:\\Miniconda3-x64"

platform:
  - x64

init:
  - "ECHO %PYTHON% %MINICONDA% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - "python -VV"
  - cmd: conda update --yes --quiet conda
  - cmd: conda config --set always_yes yes
  - cmd: conda config --add channels conda-forge
  - cmd: conda info
  - cmd: conda list
  - cmd: conda search landlab
  - cmd: conda env create -f environment-dev.yml
  - cmd: conda activate umami-dev
  - cmd: conda info
  - cmd: conda list

build: false

test_script:
  - pip install -e .
  - pytest -vvv

artifacts:
  - path: 'dist\*'
