environment:
  TWINE_PASSWORD:
    secure: 7/AZVv0ovctfsb6fBFuC84eyDbvrPSwFlwtIR5RKvQ0=
  matrix:

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python38-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python37-x64"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python36-x64"

platform:
  - x64

init:
  - "ECHO %PYTHON% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -VV"
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install pytest
  - cmd: pip install numpy
  - cmd: conda install rasterio -c conda-forge
  - cmd: pip install jupyter pandas plotnine holoviews tqdm
  - cmd: pip install landlab --pre
  - cmd: pip install terrainbento --pre

build: false

test_script:
  - pip install -e .
  - pytest -vvv

artifacts:
  - path: 'dist\*'
