environment:
  TWINE_PASSWORD:
    secure: 7/AZVv0ovctfsb6fBFuC84eyDbvrPSwFlwtIR5RKvQ0=
  matrix:

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python38-x64"
      MINICONDA: "C:\\Miniconda3"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python37-x64"
      MINICONDA: "C:\\Miniconda3"

    - TARGET_ARCH: x64
      PYTHON: "C:\\Python36-x64"
      MINICONDA: "C:\\Miniconda3"

platform:
  - x64

init:
  - "ECHO %PYTHON% %MINICONDA% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -VV"
  - cmd: python -m pip install --upgrade pip
  - cmd: pip install numpy
  - cmd: pip install statsmodels
  - cmd: pip install --pre landlab
  - cmd: pip install twine pytest pytest-cov pytest-datadir
  - cmd: pip install jupyter pandas plotnine holoviews tqdm
  - cmd: pip install --pre landlab
  - cmd: pip install --pre terrainbento
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: conda config --set always_yes yes
  - cmd: conda install rasterio -c conda-forge

build: false

test_script:
  - pip install -e .
  - pytest -vvv

artifacts:
  - path: 'dist\*'
