environment:
  TWINE_PASSWORD:
    secure: 7/AZVv0ovctfsb6fBFuC84eyDbvrPSwFlwtIR5RKvQ0=
  matrix:

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda37-x64
      CONDA_PY: 3.7

    - TARGET_ARCH: x64
      CONDA_NPY: 111
      CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
      CONDA_PY: 3.6

platform:
  - x64

os: Previous Visual Studio 2015

init:
  - "ECHO %CONDA_INSTALL_LOCN% %CONDA_PY% %HOME% %PLATFORM%"
  - "ECHO %APPVEYOR_REPO_BRANCH%"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda config --set always_yes yes
  - cmd: pip install pytest
  - cmd: pip install jupyter pandas plotnine holoviews terrainbento tqdm
  - cmd: conda install rasterio -c conda-forge
  - cmd: conda install landlab -c conda-forge
  - cmd: conda info
  - cmd: conda list

build: false

test_script:
  - pip install numpy
  - pip install -e .
  - pytest -vvv

artifacts:
  - path: 'dist\*'
