name: umami-dev
channels:
  - conda-forge
dependencies:
   - python>=3.6
   # for development
   - black
   - flake8
   - isort
   - pytest
   - pytest-cov
   # for the package
   - scipy
   - numpy
   - landlab>=2.0b4
   # for the notebooks
   - jupyter
   - holoviews
   - pandas
   - tqdm
   - plotnine>=0.6.0
   - terrainbento>=2.0
   - gdal
   - rasterio
