#!/bin/bash

conda config --add channels conda-forge
conda config --set channel_priority strict

conda install jupyter
conda install holoviews
conda install pandas
conda install plotnine>=0.6.0
conda install terrainbento>=1.10.1
conda install tqdm
conda install rasterio

python setup.py install
